# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-04-03 13:50
from __future__ import unicode_literals

import bitfield.models
import corecms.fields
import corecms.models.base_element
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import picklefield.fields
import positions.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_lang', models.BooleanField(default=True, verbose_name='Dost\u0119pne w wybranym j\u0119zyku')),
                ('for_lang_pl', models.BooleanField(default=True, verbose_name='Dost\u0119pne w wybranym j\u0119zyku')),
                ('template', models.CharField(blank=True, max_length=255, null=True, verbose_name='Szablon')),
                ('status', models.IntegerField(choices=[(0, b'Ukryty'), (1, b'Publikowany')], default=0, verbose_name='Status')),
                ('identity', models.CharField(default=b'', max_length=255, verbose_name='Tytu\u0142')),
                ('identity_pl', models.CharField(default=b'', max_length=255, null=True, verbose_name='Tytu\u0142')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ostatnia aktualizacja')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('article_date', models.DateTimeField(default=datetime.datetime.now, help_text='Data wy\u015bwietlana przy artykule', verbose_name='Data')),
                ('shortcut', corecms.fields.CMSTextField(verbose_name='Skr\xf3t')),
                ('slug', models.SlugField(blank=True, help_text='Unikalny identyfikator kategorii (opcjonalny)', max_length=255, verbose_name='Klucz')),
                ('slug_pl', models.SlugField(blank=True, help_text='Unikalny identyfikator kategorii (opcjonalny)', max_length=255, null=True, verbose_name='Klucz')),
                ('content', corecms.fields.CMSTextField(blank=True, default=b'', verbose_name='Tre\u015b\u0107')),
                ('content_pl', corecms.fields.CMSTextField(blank=True, default=b'', null=True, verbose_name='Tre\u015b\u0107')),
                ('thumbnail', corecms.fields.Base64ImageField(blank=True, null=True, upload_to=b'', verbose_name='Miniaturka')),
                ('main_image', corecms.fields.Base64ImageField(blank=True, null=True, upload_to=b'', verbose_name='Obrazek przewodni')),
                ('alternative_url', models.CharField(blank=True, default=b'', help_text=b'Link na kt\xc3\xb3ry bedzie wskazywa\xc5\x82a ten artyku\xc5\x82', max_length=255, verbose_name='Link alternatywny')),
                ('old_cms_id', models.IntegerField(default=None, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'ordering': ['-article_date'],
                'abstract': False,
                'verbose_name': 'Artyku\u0142',
                'verbose_name_plural': 'Artyku\u0142y',
            },
            bases=(corecms.models.base_element.ConnectedFilesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ConfigCMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(blank=True, default=b'', max_length=255, verbose_name='Tytu\u0142 strony')),
                ('site_pagination', models.IntegerField(default=5, verbose_name='Ilo\u015b\u0107 artyku\u0142\xf3w na jednej stronie')),
                ('seo_keywords', models.CharField(blank=True, default=b'', help_text='Rozdzielaj przecinkiem', max_length=255, verbose_name='S\u0142owa kluczowe')),
                ('seo_description', models.TextField(blank=True, default=b'', verbose_name='Opis w META')),
                ('tracking_code', models.TextField(blank=True, default=b'', verbose_name='Kod \u015bledz\u0105cy w znaczniku HEAD')),
                ('cookie_description', models.TextField(blank=True, default=b'', help_text='Je\u017celi puste to informacja b\u0119dzie niewidoczna', verbose_name='Informacja w informacji o ciastkach')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Konfiguracja',
                'verbose_name_plural': 'Konfiguracja',
            },
        ),
        migrations.CreateModel(
            name='FormGeneratorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('emails', models.TextField(blank=True, null=True, verbose_name='E-Maile rozdzielone przecinkami')),
                ('form_data', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('for_lang', models.BooleanField(default=True, verbose_name='Dost\u0119pne w wybranym j\u0119zyku')),
            ],
            bases=(corecms.models.base_element.ConnectedFilesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='IsSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cms_id', models.IntegerField()),
                ('is_site', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_lang', models.BooleanField(default=True, verbose_name='Dost\u0119pne w wybranym j\u0119zyku')),
                ('for_lang_pl', models.BooleanField(default=True, verbose_name='Dost\u0119pne w wybranym j\u0119zyku')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(default=b'', max_length=255, verbose_name=b'Oryginalna nazwa pliku')),
                ('title', models.CharField(default=b'', max_length=255, verbose_name=b'Tytu\xc5\x82 pliku')),
                ('path', models.FilePathField(max_length=1000)),
                ('position', positions.fields.PositionField(default=0)),
                ('distinction', bitfield.models.BitField(((b'downloadable', 'Do pobrania', b'glyphicon-download-alt'), (b'gallery', 'Galeria', b'glyphicon-picture'), (b'cover', 'Poka\u017c ok\u0142adk\u0119', b'glyphicon-book')), default=None)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name=b'Data utworzenia')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name=b'Typ pliku')),
                ('file_size', models.CharField(blank=True, max_length=200, verbose_name=b'Rozmiar pliku')),
                ('description', models.TextField(blank=True, max_length=250, verbose_name=b'Opis')),
                ('repository', models.BooleanField(default=False, verbose_name='W repozytorium')),
                ('publish', models.BooleanField(default=True, verbose_name='Publikuj na www')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Utworzone przez')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ghost_files', to='cms.MediaFile')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('slug', models.SlugField(help_text='Unikalny identyfikator', max_length=32, verbose_name='Klucz')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='RelationArticleSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', positions.fields.PositionField(default=-1)),
                ('main', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Article')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RelationMenuSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', positions.fields.PositionField(default=-1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(blank=True, max_length=255, null=True, verbose_name='Szablon')),
                ('status', models.IntegerField(choices=[(0, b'Ukryty'), (1, b'Publikowany')], default=0, verbose_name='Status')),
                ('identity', models.CharField(default=b'', max_length=255, verbose_name='Tytu\u0142')),
                ('identity_pl', models.CharField(default=b'', max_length=255, null=True, verbose_name='Tytu\u0142')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ostatnia aktualizacja')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('alternative_url', models.CharField(blank=True, default=b'', help_text=b'Link na kt\xc3\xb3ry bedzie wskazywa\xc5\x82a ta strona', max_length=255, verbose_name='Link alternatywny')),
                ('thumbnail', corecms.fields.Base64ImageField(blank=True, null=True, upload_to=b'', verbose_name='Miniaturka')),
                ('main_image', corecms.fields.Base64ImageField(blank=True, null=True, upload_to=b'', verbose_name='Obrazek przewodni')),
                ('slug', models.SlugField(blank=True, help_text='Unikalny identyfikator kategorii (opcjonalny)', max_length=255, verbose_name='Klucz')),
                ('slug_pl', models.SlugField(blank=True, help_text='Unikalny identyfikator kategorii (opcjonalny)', max_length=255, null=True, verbose_name='Klucz')),
                ('content', corecms.fields.CMSTextField(blank=True, default=b'', verbose_name='Tre\u015b\u0107')),
                ('content_pl', corecms.fields.CMSTextField(blank=True, default=b'', null=True, verbose_name='Tre\u015b\u0107')),
                ('order', models.PositiveIntegerField(default=0)),
                ('old_cms_id', models.IntegerField(default=None, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('articles', models.ManyToManyField(through='cms.RelationArticleSite', to='cms.Article')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.Site', verbose_name='Strona nadrz\u0119dna')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ostatnio aktualizowa\u0142')),
            ],
            options={
                'ordering': ('lft',),
                'abstract': False,
                'verbose_name': 'Strona',
                'verbose_name_plural': 'Strony',
            },
            bases=(corecms.models.base_element.ConnectedFilesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Identyfikator')),
                ('name', models.CharField(blank=True, default=b'', max_length=255, verbose_name='Nazwa')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Slidery',
            },
        ),
        migrations.CreateModel(
            name='SliderRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=b'', max_length=255, verbose_name='Nazwa')),
                ('text', models.TextField(blank=True, default=b'', verbose_name='Opis')),
                ('image', models.ImageField(blank=True, upload_to=b'public/sliders', verbose_name='Obrazek')),
                ('order', models.IntegerField(default=1, verbose_name='Priorytet')),
                ('status', models.IntegerField(choices=[(0, b'Ukryty'), (1, b'Publikowany')], default=1, verbose_name='Status')),
                ('url', models.CharField(blank=True, default=b'', max_length=255, verbose_name='Url')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.Slider')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
                'verbose_name': 'Slider - wpis',
                'verbose_name_plural': 'Slider - wpisy',
            },
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.SlugField(max_length=255, unique=True, verbose_name='Identyfikator')),
                ('content', models.TextField(blank=True, default=b'', verbose_name='Tre\u015b\u0107')),
                ('content_pl', models.TextField(blank=True, default=b'', null=True, verbose_name='Tre\u015b\u0107')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Blok tekstowy',
                'verbose_name_plural': 'Bloki tekstowe',
            },
            bases=(corecms.models.base_element.ConnectedFilesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
            ],
            options={
                'verbose_name': 'Tag',
                'proxy': True,
                'verbose_name_plural': 'Tagi',
                'indexes': [],
            },
            bases=('taggit.tag',),
        ),
        migrations.AddField(
            model_name='relationmenusite',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Site'),
        ),
        migrations.AddField(
            model_name='relationmenusite',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Menu'),
        ),
        migrations.AddField(
            model_name='relationarticlesite',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Site'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tagi'),
        ),
        migrations.AddField(
            model_name='article',
            name='sites',
            field=models.ManyToManyField(through='cms.RelationArticleSite', to='cms.Site'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tagi'),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ostatnio aktualizowa\u0142'),
        ),
        migrations.CreateModel(
            name='RepositoryMediaFile',
            fields=[
            ],
            options={
                'verbose_name': 'Plik',
                'proxy': True,
                'verbose_name_plural': 'Repozytorium plik\xf3w',
                'indexes': [],
            },
            bases=('cms.mediafile',),
        ),
        migrations.AlterUniqueTogether(
            name='relationmenusite',
            unique_together=set([('child', 'parent')]),
        ),
        migrations.AlterUniqueTogether(
            name='relationarticlesite',
            unique_together=set([('child', 'parent')]),
        ),
    ]
