# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-03-28 09:17
from __future__ import unicode_literals

import bitfield.models
import corecms.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='for_lang',
            field=models.BooleanField(default=True, verbose_name='Dostępne w wybranym języku'),
        ),
        migrations.AlterField(
            model_name='article',
            name='alternative_url',
            field=models.CharField(blank=True, default='', help_text='Link na który bedzie wskazywała ten artykuł', max_length=255, verbose_name='Link alternatywny'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=corecms.fields.CMSTextField(blank=True, default='', verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_pl',
            field=corecms.fields.CMSTextField(blank=True, default='', null=True, verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='article',
            name='identity',
            field=models.CharField(default='', max_length=255, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='article',
            name='identity_pl',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=corecms.fields.Base64ImageField(blank=True, null=True, upload_to='', verbose_name='Obrazek przewodni'),
        ),
        migrations.AlterField(
            model_name='article',
            name='shortcut',
            field=corecms.fields.CMSTextField(blank=True, default='', verbose_name='Skrót'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ukryty'), (1, 'Publikowany')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=corecms.fields.Base64ImageField(blank=True, null=True, upload_to='', verbose_name='Miniaturka'),
        ),
        migrations.AlterField(
            model_name='configcms',
            name='cookie_description',
            field=models.TextField(blank=True, default='', help_text='Jeżeli puste to informacja będzie niewidoczna', verbose_name='Informacja w informacji o ciastkach'),
        ),
        migrations.AlterField(
            model_name='configcms',
            name='seo_description',
            field=models.TextField(blank=True, default='', verbose_name='Opis w META'),
        ),
        migrations.AlterField(
            model_name='configcms',
            name='seo_keywords',
            field=models.CharField(blank=True, default='', help_text='Rozdzielaj przecinkiem', max_length=255, verbose_name='Słowa kluczowe'),
        ),
        migrations.AlterField(
            model_name='configcms',
            name='site_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tytuł strony'),
        ),
        migrations.AlterField(
            model_name='configcms',
            name='tracking_code',
            field=models.TextField(blank=True, default='', verbose_name='Kod śledzący w znaczniku HEAD'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utworzone przez'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='description',
            field=models.TextField(blank=True, max_length=250, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='distinction',
            field=bitfield.models.BitField((('downloadable', 'Do pobrania', 'glyphicon-download-alt'), ('gallery', 'Galeria', 'glyphicon-picture'), ('cover', 'Pokaż okładkę', 'glyphicon-book')), default=None),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file_size',
            field=models.CharField(blank=True, max_length=200, verbose_name='Rozmiar pliku'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Typ pliku'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Oryginalna nazwa pliku'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='path',
            field=models.FilePathField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Tytuł pliku'),
        ),
        migrations.AlterField(
            model_name='site',
            name='alternative_url',
            field=models.CharField(blank=True, default='', help_text='Link na który bedzie wskazywała ta strona', max_length=255, verbose_name='Link alternatywny'),
        ),
        migrations.AlterField(
            model_name='site',
            name='content',
            field=corecms.fields.CMSTextField(blank=True, default='', verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='site',
            name='content_pl',
            field=corecms.fields.CMSTextField(blank=True, default='', null=True, verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='site',
            name='identity',
            field=models.CharField(default='', max_length=255, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='site',
            name='identity_pl',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='site',
            name='main_image',
            field=corecms.fields.Base64ImageField(blank=True, null=True, upload_to='', verbose_name='Obrazek przewodni'),
        ),
        migrations.AlterField(
            model_name='site',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ukryty'), (1, 'Publikowany')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='site',
            name='thumbnail',
            field=corecms.fields.Base64ImageField(blank=True, null=True, upload_to='', verbose_name='Miniaturka'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='sliderrow',
            name='image',
            field=models.ImageField(blank=True, upload_to='public/sliders', verbose_name='Obrazek'),
        ),
        migrations.AlterField(
            model_name='sliderrow',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='sliderrow',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ukryty'), (1, 'Publikowany')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sliderrow',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='sliderrow',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='content_pl',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Treść'),
        ),
    ]
