# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-04-11 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20170403_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryDistinction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_global', models.BooleanField(default=False)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Gallery')),
            ],
        ),
    ]
