# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-31 13:05
from __future__ import unicode_literals

import corecms.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20170330_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cms_id', models.IntegerField()),
                ('is_site', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=corecms.fields.Base64ImageField(blank=True, null=True, upload_to='', verbose_name='Obrazek przewodni'),
        ),
        migrations.AlterField(
            model_name='article',
            name='shortcut',
            field=corecms.fields.CMSTextField(verbose_name='Skrót'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=corecms.fields.Base64ImageField(blank=True, null=True, upload_to='', verbose_name='Miniaturka'),
        ),
        migrations.AlterField(
            model_name='site',
            name='main_image',
            field=corecms.fields.Base64ImageField(blank=True, null=True, upload_to='', verbose_name='Obrazek przewodni'),
        ),
        migrations.AlterField(
            model_name='site',
            name='thumbnail',
            field=corecms.fields.Base64ImageField(blank=True, null=True, upload_to='', verbose_name='Miniaturka'),
        ),
    ]
