# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_gallerydistinction'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='youtube',
            field=models.CharField(blank=True, default=b'', max_length=1000, verbose_name=b'Youtube'),
        ),
    ]
