# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_mediafile_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='budget',
            field=models.CharField(blank=True, default=b'', max_length=255, verbose_name='Bud\u017cet ca\u0142kowity'),
        ),
        migrations.AddField(
            model_name='site',
            name='execution_time',
            field=models.CharField(blank=True, default=b'', max_length=255, verbose_name='Czas realizacji'),
        ),
        migrations.AddField(
            model_name='site',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b'site/images/', verbose_name=b'Logo'),
        ),
    ]
