# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-31 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20170331_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='old_cms_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='old_cms_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
