# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_site_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('logo', models.ImageField(upload_to=b'site/founder/images/', verbose_name=b'Logo')),
                ('url', models.URLField(blank=True, default=b'', verbose_name='Link')),
            ],
        ),
    ]
