# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_founder'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cms.Site'),
            preserve_default=False,
        ),
    ]
