# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_founder_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='url',
            field=models.URLField(blank=True, default=b'', verbose_name='Link'),
        ),
    ]
