# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_article_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Projekt archiwalny'),
        ),
    ]
